REM ****** Populating Musician Database

INSERT INTO MUSICIAN VALUES( 1,'SPB','CHENNAI');
INSERT INTO MUSICIAN VALUES( 2,'MSV','MUMBAI');
INSERT INTO MUSICIAN VALUES( 3,'KJY','KERALA');


REM ****** Populating Studio Database

INSERT INTO STUDIO VALUES( 'A','CHENNAI',1234567890);
INSERT INTO STUDIO VALUES( 'B','MUMBAI', 9876543210);
INSERT INTO STUDIO VALUES( 'C','KERALA', 2345678910);

REM ****** Populating Album Database

INSERT INTO ALBUM VALUES( 1,'INDIGO',2019,30,'A','POP',2);
INSERT INTO ALBUM VALUES( 2,'BOMBAY',1996,8,'B','DIV',3);
INSERT INTO ALBUM VALUES( 3,'BIGIL',2017,3,'C','MOV',1);


REM ****** Populating Song Database

INSERT INTO SONG VALUES( 1,1,'UNDECIDED',123,'REL');
INSERT INTO SONG VALUES( 2,1,'RED',321,'LOV');
INSERT INTO SONG VALUES( 3,2,'ARABIAN SEA',23,'PAT');
INSERT INTO SONG VALUES( 3,2,'ARABIAN SEA',23,'PHI');
REM ****** Violating song length for 'PAT'
INSERT INTO SONG VALUES( 3,3,'BIGILEYYYY',5,'PAT');


REM ****** Populating Artist Database

INSERT INTO ARTIST VALUES( 1,'SHARVAN');
INSERT INTO ARTIST VALUES( 2,'SHASHU');
INSERT INTO ARTIST VALUES( 3,'SIDDHARTH');

REM ****** Populating Sungby Database

INSERT INTO SUNGBY VALUES( 1,2,1,'25-JUL-2019');
INSERT INTO SUNGBY VALUES( 1,2,2,'15-FEB-2018');
INSERT INTO SUNGBY VALUES( 2,1,3,'05-AUG-2017');
INSERT INTO SUNGBY VALUES( 2,3,3,'03-MAY-1996');

REM ****** Musician Database
SELECT * FROM MUSICIAN;

REM ****** Album Database
SELECT * FROM ALBUM;

REM ****** Song Database
SELECT * FROM SONG;

REM ****** Artist Database
SELECT * FROM ARTIST;

REM ****** Sungby Database
SELECT * FROM SUNGBY;

REM ****** Studio Database
SELECT * FROM STUDIO;
