
DROP TABLE SUNGBY;
DROP TABLE ARTIST;
DROP TABLE SONG;
DROP TABLE ALBUM;
DROP TABLE STUDIO;
DROP TABLE MUSICIAN;

REM ****** Musician Database

CREATE TABLE MUSICIAN(
	MUSICIAN_ID NUMBER(5), 
	MUSICIAN_NAME VARCHAR2(20),
	BIRTHPLACE VARCHAR2(20),
	CONSTRAINT music_pk PRIMARY KEY (MUSICIAN_ID)
);

REM ****** Studio Database

CREATE TABLE STUDIO(
	STUDIO_NAME VARCHAR2(20) CONSTRAINT studio_pk PRIMARY KEY,
	STUDIO_ADDRESS VARCHAR2(20),
	STUDIO_PHONE NUMBER(10)
);

REM ****** Album Database 

CREATE TABLE ALBUM(
	ALBUM_ID NUMBER(5) CONSTRAINT album_pk PRIMARY KEY,
	ALBUM_NAME VARCHAR2(20),
	YEAR_RELEASE NUMBER(4) CONSTRAINT check_year CHECK(YEAR_RELEASE>1945),
	NO_TRACKS NUMBER(3) CONSTRAINT album_track_null NOT NULL,
	STUDIO VARCHAR2(20) CONSTRAINT album_studio_fk REFERENCES STUDIO(STUDIO_NAME),
	GENRE VARCHAR2(3) CONSTRAINT check_genre  CHECK(genre in ('CAR','DIV','MOV','POP')),
	MUSICIAN NUMBER(5) CONSTRAINT album_musician_fk REFERENCES MUSICIAN(MUSICIAN_ID)
);

REM ******* Song Database

CREATE TABLE SONG(
	TRACK_NO NUMBER(3),
	ALBUM_ID NUMBER(5) CONSTRAINT song_fk REFERENCES ALBUM(ALBUM_ID),
	SONG_NAME VARCHAR2(20),
	SONG_LENGTH NUMBER(3),
	SONG_GENRE VARCHAR2(3) CONSTRAINT check_song CHECK(SONG_GENRE IN('REL','PHI','LOV','DEV','PAT')), 
	CONSTRAINT song_pk PRIMARY KEY(ALBUM_ID,TRACK_NO),
	CONSTRAINT check_length CHECK(SONG_GENRE!='PAT' OR SONG_LENGTH>7) 
);

REM ****** Artist Database

CREATE TABLE ARTIST(
	ARTIST_ID NUMBER(5) CONSTRAINT artist_pk PRIMARY KEY,
	ARTIST_NAME VARCHAR2(20) 
);

REM ****** SungBy Database

CREATE TABLE SUNGBY(
	ALBUM_ID NUMBER(5),
	ARTIST_ID NUMBER(5),
	TRACK_NO NUMBER(3),
	RECORDING_DATE DATE,
	CONSTRAINT sungby_pk PRIMARY KEY(ALBUM_ID,ARTIST_ID,TRACK_NO),
	CONSTRAINT sungby_fk FOREIGN KEY(ALBUM_ID,TRACK_NO) REFERENCES SONG(ALBUM_ID,TRACK_NO),
	CONSTRAINT sungby_fk1 FOREIGN KEY(ARTIST_ID) REFERENCES ARTIST(ARTIST_ID)
);



